version: '3.5'

services:

  input_db:
    container_name: input_db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2.sql
    ports: [ "6000:5432" ]
    healthcheck:
      test: "pg_isready -d postgres -q -U ${POSTGRES_USER:-postgres}"
      interval: "3s"
      timeout: "3s"
      start_period: "3s"
      retries: 30


  output_db:
    container_name: output_db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1.sql
    ports: [ "6001:5432" ]
    healthcheck:
      test: "pg_isready -d postgres -q -U ${POSTGRES_USER:-postgres}"
      interval: "3s"
      timeout: "3s"
      start_period: "3s"
      retries: 30


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "8888:80"


  databases:
    container_name: databases
    image: docker/whalesay
    command: >
      cowsay
        "Both the source and target databases have been started on
         port 6000 and 6001 respectively, and are ready for TDK exercises!
         To check it out with pgAdmin, simply go to this link:
         http://localhost:8888 and use 'postgres' as the password."
    depends_on:
      input_db:
        condition: service_healthy
      output_db:
        condition: service_healthy
      pgadmin:
        condition: service_started


  check:
    container_name: check
    image: sodadata/soda-core
    volumes:
      - ./soda:/sodacl
